# SITE CONFIGURATION
baseurl: ""
url: "https://jungwoon.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Jungwoon Blog
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
#  header_text: >
#     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
#
#     <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
#  header_text_feature_image:
<<<<<<< HEAD
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>
=======
#  footer_text: >
#   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>
>>>>>>> posting

  # Icons
  rss: false
  email_address: "byjungwoon@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "byjw.park"
  flickr:
  gitlab:
  github: "jungwoon"
  gitter:
  google_plus:
  instagram:
<<<<<<< HEAD
  linkedin:  "https://www.linkedin.com/in/jungwoon-park/" # Full URL
=======
  linkedin:  # Full URL
>>>>>>> posting
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-79172120-2" # Tracking ID, e.g. "UA-000000-01"
<<<<<<< HEAD
  disqus_shortname: "jungwoon"
=======
  disqus_shortname:
>>>>>>> posting
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
<<<<<<< HEAD
  str_email: "이메일"
  str_next_post: "다음 포스트"
  str_previous_post: "이전 포스트"
  str_next_page: "다음"
  str_previous_page: "이전"
  str_continue_reading: "자세히 보기"
  str_javascript_required_disqus: "Comments를 확인하려면 Java스크립트를 활성화 하여야 합니다."
  str_search_no_results: "검색 결과가 없습니다"
=======
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."
>>>>>>> posting

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
<<<<<<< HEAD
paginate: 15
=======
paginate: 5
>>>>>>> posting
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
