# Site settings
title: Jungwoon Blog
header-img: img/home-bg.jpg
email: byjungwoon@gmail.com
copyright_name: byJW
description: "Everything You need for development"
baseurl: ""
url: "http://jungwoon.github.io"
twitter_username: byPJW
github_username:  jungwoon
facebook_username:  byjw.park
email_username:  byjungwoon@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-79172120-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-minimal